### ISSUE TITLE
failed to build develop environment

### ISSUE THREAD

**Issue by xidianwlc** [Automattic/simplenote-electron#351]
#### Steps to reproduce
1.  git clone https://github.com/Automattic/simplenote-electron.git
2.  npm install
3.  npm run build
4.  electron .

#### What I expected
after electron . commond , simplenote should be builded, but it failed for Error: Cannot find module 'app'

#### What happened instead
```
web@ubuntu:~/workspace/simplenote-master$ npm run build

> simplenote@1.0.2 build /home/web/workspace/simplenote-master
> NODE_ENV=development `npm bin`/webpack --config ./webpack.config.js

no configuration file present
Hash: d8b125734042e42b93cd
Version: webpack 1.12.14
Time: 26489ms
            Asset       Size  Chunks             Chunk Names
           app.js    2.47 MB       0  [emitted]  main
       app.js.map    2.98 MB       0  [emitted]  main
manifest.appcache   69 bytes          [emitted]  
       index.html  554 bytes          [emitted]  
   [0] multi main 28 bytes {0} [built]
    + 445 hidden modules
web@ubuntu:~/workspace/simplenote-master$ electron .
App threw an error during load
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/home/web/env/node/lib/node_modules/.electron_npminstall/node_modules/.electron@1.3.1/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/web/workspace/simplenote-master/desktop/app.js:3:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
A JavaScript error occurred in the main process
Uncaught Exception:
Error: Cannot find module 'app'
    at Module._resolveFilename (module.js:440:15)
    at Function.Module._resolveFilename (/home/web/env/node/lib/node_modules/.electron_npminstall/node_modules/.electron@1.3.1/dist/resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:388:25)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/home/web/workspace/simplenote-master/desktop/app.js:3:11)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
```

#### OS version
ubuntu 14.04

**Comment by xidianwlc** [comment]
because of electron api is change

**Comment by artivilla** [comment]
Were you able to get this to work? Having the same issues.
